version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - certificate-network
    restart: unless-stopped

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-certificates}
      - SESSION_SECRET=${SESSION_SECRET:-your-session-secret-change-me}
      - ALLOWED_ORIGINS=http://localhost:3000,${FRONTEND_URL:-http://localhost:3000}
    volumes:
      - uploads:/app/uploads
      - temp:/app/temp
      - fonts:/app/fonts
    depends_on:
      - db
    networks:
      - certificate-network
    restart: unless-stopped

  # Database service
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-certificates}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - certificate-network
    restart: unless-stopped

networks:
  certificate-network:
    driver: bridge

volumes:
  postgres-data:
  uploads:
  temp:
  fonts: