services:
  # الواجهة الخلفية - API
  - type: web
    name: certificates-api
    env: node
    region: frankfurt  # يمكن تغييره حسب المنطقة المناسبة
    plan: starter  # يمكن تغييره حسب الخطة المطلوبة
    buildCommand: chmod +x server/render-build.sh && ./server/render-build.sh
    startCommand: node server/dist/index.js
    healthCheckPath: /health/ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: certificates-db
          property: connectionString
      - key: ALLOWED_ORIGINS
        value: "https://certificates-frontend.onrender.com"

  # الواجهة الأمامية - React
  - type: web
    name: certificates-frontend
    env: static
    region: frankfurt  # يمكن تغييره حسب المنطقة المناسبة
    buildCommand: chmod +x client/render-build.sh && ./client/render-build.sh
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: "https://certificates-api.onrender.com"

databases:
  # قاعدة البيانات Postgres
  - name: certificates-db
    plan: starter  # يمكن تغييره حسب الخطة المطلوبة
    region: frankfurt  # يمكن تغييره حسب المنطقة المناسبة
    ipAllowList: []  # السماح للجميع بالوصول
    postDeploy: |
      npm run db:init